version: "3.8"
services:
  prometheus:
    image: prom/prometheus:v2.45.0-rc.1
    container_name: prometheus
    user: root
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus_data:/prometheus_data    
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus_data'
      - '--storage.tsdb.retention.time=60d'
      - '--storage.tsdb.retention.size=10GB'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    network_mode: host

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    user: root
    restart: unless-stopped
    depends_on:
      - prometheus
    volumes:
      - ./data/grafana_data:/var/lib/grafana
      - ./grafana/etc:/etc/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=$GRAFANA_USER
      - GF_SECURITY_ADMIN_PASSWORD=$GRAFANA_PASSWORD
      - GF_USERS_ALLOW_SIGN_UP=false
    network_mode: host

  json-exporter:
    image: quay.io/prometheuscommunity/json-exporter
    container_name: json-exporter
    restart: unless-stopped
    volumes:
      - ./prometheus/exporters/json-exporter/config.yml:/config.yml
    command:
      - '--config.file=/config.yml'
    network_mode: host

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    network_mode: host

  blackbox-exporter:
    image: prom/blackbox-exporter
    container_name: blackbox-exporter
    restart: unless-stopped
    volumes:
      - ./prometheus/exporters/blackbox-exporter/config.yml:/config.yml
    command:
      - '--config.file=/config.yml'
    network_mode: host
